name: GDLauncher Next CI

on:
  push:
    branches:
      - next
      - deploy
  pull_request:
    branches:
      - next
      - deploy
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: yarn install
        run: |
          yarn install
      - name: yarn lint
        run: |
          yarn lint
      - name: yarn release
        env:
          CI: false
          TRAVIS_TAG: false
          APPVEYOR_REPO_TAG_NAME: false
          CIRCLE_TAG: false
          BITRISE_GIT_TAG: false
          CI_BUILD_TAG: false
        run: |
          yarn release
      - name: upload release to github
        if: |
          (github.event_name == 'push' && contains(github.event.ref, '/deploy'))
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          node ./scripts/uploadRelease.js
        shell: bash

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'macos-latest'
        with:
          name: MacOs Release
          path: deploy

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'windows-latest'
        with:
          name: Windows Release
          path: deploy

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Linux Release
          path: deploy

      - uses: actions/setup-ruby@v1
      - name: Send Webhook Notification
        if: matrix.os == 'macos-latest'
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          git clone https://github.com/gorilla-devs/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
